/**
 * Rust ↔ TS v0.2 cross-language compatibility test.
 *
 * Asserts that TS v0.2 (`mnemonic-rust-compat.ts` +
 * `sealed-box-rust-compat.ts` + `montgomery.ts`) reproduces the
 * exact byte output of the Rust reference, and decrypts a
 * sealed-box payload that Rust produced.
 *
 * Vectors generated by:
 *   cargo run -p tardus-wallet --example cross_language_vectors --release
 *
 * The `master_seed` + `recv_sk` + `recv_pk` are FULLY deterministic
 * (BIP-39 + HKDF), so re-running the Rust example gives the same
 * values. `sealed_box_hex` varies per Rust run (random ephemeral
 * key); the committed vector below is one specific Rust sample.
 *
 * License: TARDUS-PROPRIETARY-1.0.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  deriveMasterSeedRustCompat,
  deriveReceivingKeypairRustCompat,
} from '../src/mnemonic-rust-compat.ts';
import { openRustCompat } from '../src/sealed-box-rust-compat.ts';

/** One sample vector from `cargo run -p tardus-wallet --example cross_language_vectors`. */
const RUST_VECTORS = {
  mnemonic:
    'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
  master_seed_hex:
    '5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc1',
  recv_sk_hex:
    'b4fecd6839630d54e244174662dea70ad376b89d0dbbf26756f173d4924bb60c',
  recv_pk_hex:
    'be7a337ae6b05629e16ca56161973a95687be0afb6cf6b2ab4f0c23935855614',
  plaintext_hex:
    '7461726475732063726f73732d6c616e6775616765207465737420766563746f72207631',
  sealed_box_hex:
    'de5fe33ce7686421a0ad2855a3c46f5ec6502debceb831b22ae68e477cb74c69de7af904b8b8bdbefe1681a1dd775d3ee8500c40b4c956ae2788ecfcb6b2375ce44e05bc8add6f1c28a46b566e85b39cf3ffe7fd',
} as const;

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(b: Uint8Array): string {
  return Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');
}

test('Rust master_seed byte-equal in TS', () => {
  const seed = deriveMasterSeedRustCompat(RUST_VECTORS.mnemonic, '');
  assert.equal(
    bytesToHex(seed),
    RUST_VECTORS.master_seed_hex,
    'TS deriveMasterSeedRustCompat must produce exactly the Rust output',
  );
});

test('Rust recv_sk + recv_pk byte-equal in TS', () => {
  const seed = deriveMasterSeedRustCompat(RUST_VECTORS.mnemonic, '');
  const { sk, pk } = deriveReceivingKeypairRustCompat(seed);
  assert.equal(
    bytesToHex(sk),
    RUST_VECTORS.recv_sk_hex,
    'TS recv_sk must match Rust recv_sk',
  );
  assert.equal(
    bytesToHex(pk),
    RUST_VECTORS.recv_pk_hex,
    'TS recv_pk must match Rust recv_pk',
  );
});

test('TS decrypts Rust-produced sealed_box (wire compatibility)', () => {
  const sk = hexToBytes(RUST_VECTORS.recv_sk_hex);
  const sealed = hexToBytes(RUST_VECTORS.sealed_box_hex);
  const recovered = openRustCompat(sealed, sk);
  assert.equal(
    bytesToHex(recovered),
    RUST_VECTORS.plaintext_hex,
    'TS openRustCompat MUST decrypt the Rust-sealed payload to the same plaintext',
  );
  assert.equal(
    new TextDecoder().decode(recovered),
    'tardus cross-language test vector v1',
  );
});

test('full chain: Rust mnemonic → TS keypair → Rust ciphertext → TS plaintext', () => {
  // End-to-end verification: derive the keypair from the
  // mnemonic in TS, then decrypt the Rust-produced ciphertext
  // with the derived sk.
  const seed = deriveMasterSeedRustCompat(RUST_VECTORS.mnemonic, '');
  const { sk, pk } = deriveReceivingKeypairRustCompat(seed);

  // sanity: derived pk matches what Rust embedded as the
  // recipient of the sealed-box.
  assert.equal(bytesToHex(pk), RUST_VECTORS.recv_pk_hex);

  const sealed = hexToBytes(RUST_VECTORS.sealed_box_hex);
  const recovered = openRustCompat(sealed, sk);
  assert.equal(bytesToHex(recovered), RUST_VECTORS.plaintext_hex);
});
